name: CD-Pipeline

on:
  workflow_dispatch: {}           # manual trigger
  repository_dispatch:           # triggered from CI
    types: [ci-completed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show event
        run: |
          echo "Event name: ${{ github.event_name }}"
